/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js during local development.
// It is included here so TypeScript tooling has the expected references in repository previews.
